import type { Metadata } from 'next';
import React from 'react';

import { nunito } from '@/styles/fonts';
import '@/styles/globals.css';

import AppFooter from '@/components/layouts/footer';
import AppHeader from '@/components/layouts/header';

import { StoreProvider } from '@/context/StoreContext';
import { ThemeProvider } from '@/context/ThemeContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: [],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="light"
    >
      <body className={nunito.className}>
        <ThemeProvider>
          <StoreProvider>
            <AppHeader />
            <main className="relative container mx-auto">{children}</main>
            <AppFooter />
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
