import React from 'react';
import type { Metadata } from 'next';

import '@/styles/index.scss';

import { Mulish } from 'next/font/google';
import { keywords } from '@/configs/keywords';

import StoreProvider from './StoreProvider';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';

export const mulish = Mulish({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: keywords,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="light"
    >
      <body className={mulish.className}>
        <StoreProvider>
          <Header />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
